version: 2
jobs:
  build:
    docker: 
      - image: node:8.6.0
      - image: mongo:3.4.4
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=java@123
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_HOST=127.0.0.1

    working_directory: /home/ubuntu/hr-recruit
    
    steps:
      - checkout
      - run: mkdir -p /home/ubuntu/hr-recruit
      - run: npm install
      - run: npm run db
      - run: npm run build
      - run: npm install pm2 -g 
      - run: pm2 start npm --name recruit  -- dev
      - run: npm install -g newman
      - run: npm run test